### ISSUE TITLE
Select sim in case the multisim is supported

### ISSUE THREAD

**Issue by TakykCheshme** [shounakmulay/Telephony#100]
While testing apps using this package, I remarked that sms are sent by the first sim card on the phone with DUAL sim. You did a great job and it would be very helpful if you add this feature too :)

**Comment by shounakmulay** [comment]
Yes the package uses the default sim that the android system provides.

About adding multi sim support, I understand that this could be a very useful feature to have. 
Unfortunately I don't see myself getting the to implementing this any time soon. Although I would be happy to accept PRs.
