### ISSUE TITLE
error No implementation found for method requestPhoneAndSmsPermissions on channel plugins.shounakmulay.com/foreground_sms_channel

### ISSUE THREAD

**Issue by falahgs** [shounakmulay/Telephony#102]
Hi bro...
why i got error 

Restarted application in 3,034ms.
E/flutter ( 6235): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method requestPhoneAndSmsPermissions on channel plugins.shounakmulay.com/foreground_sms_channel)
E/flutter ( 6235): #0      MethodChannel._invokeMethod
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235): #1      _SendSMSstate.initPlatformState
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235):
E/flutter ( 6235): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method openDialer on channel plugins.shounakmulay.com/foreground_sms_channel)
E/flutter ( 6235): #0      MethodChannel._invokeMethod
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235): #1      Telephony.openDialer (package:telephony/telephony.dart:514:5)
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235): #2      _SendSMSstate.build.<anonymous closure>
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235):

and the code is 

import 'package:flutter/material.dart';
import 'dart:async';
import 'package:telephony/telephony.dart';

onBackgroundMessage(SmsMessage message) {
  debugPrint("onBackgroundMessage called");
}

//void main() {
// runApp(MyApp());
//}

class SendSMS extends StatefulWidget {
  @override
  _SendSMSstate createState() => _SendSMSstate();
}

class _SendSMSstate extends State<SendSMS> {
  String _message = "";
  final telephony = Telephony.instance;

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  onMessage(SmsMessage message) async {
    setState(() {
      _message = message.body ?? "Error reading message body.";
    });
  }

  onSendStatus(SendStatus status) {
    setState(() {
      _message = status == SendStatus.SENT ? "sent" : "delivered";
    });
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    // Platform messages may fail, so we use a try/catch PlatformException.
    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.

    final bool result = await telephony.requestPhoneAndSmsPermissions;

    if (result != null && result) {
      telephony.listenIncomingSms(
          onNewMessage: onMessage, onBackgroundMessage: onBackgroundMessage);
    }

    if (!mounted) return;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(child: Text("Latest received SMS: $_message")),
          TextButton(
              onPressed: () async {
                await telephony.openDialer("xxxxxxxxxxxx");
              },
              child: Text('Open Dialer'))
        ],
      ),
    ));
  }
}

**Comment by Lorenzo3** [comment]
I have the same error when i call "requestSmsPermissions"

```
import 'package:telephony/telephony.dart';

final teleph = Telephony.instance;
...
bool? canSend = await teleph.requestSmsPermissions;
if (canSend != null && canSend) {
   teleph.sendSms(to: homeNumber, message: message);
} else {
   print("...");
}
```

**Comment by AtomicRaven** [comment]
I have the same error in iOS only

![Screen Shot 2021-11-01 at 12 56 28 PM](https://user-images.githubusercontent.com/1229069/139710017-26ed64bc-09a8-4818-805d-d6d24049efb0.png)

**Comment by meridorkobi** [comment]
I have the same problem - the following exception

**The code** 
**telephony.sendSms(
                  to: wonderHero.toString(),
                  message: _message.toString(),
                  statusListener: listener);**
                  
                  
**The exception**

MissingPluginException(No implementation found for method sendSms on channel plugins.shounakmulay.com/foreground_sms_channel)

**Comment by ejlocop** [comment]
still getting the same issue
