### ISSUE TITLE
Sending SMS in Background 

### ISSUE THREAD

**Issue by baraaaljabban** [shounakmulay/Telephony#120]
Lib v:.01.4
I have two questions first one:

1. when I was browsing the code and I found that **backgroundInstance** and **foreground** **instantness**  are using the same channel 
both are being initialised with `_FOREGROUND_CHANNEL`, but shouldn't the backgroundInstance be instilized with `_BACKGROUND_CHANNEL` argument 
```
  static final Telephony _instance = Telephony._newInstance(
      const MethodChannel(_FOREGROUND_CHANNEL), const LocalPlatform());
  static final Telephony _backgroundInstance = Telephony._newInstance(
      const MethodChannel(_FOREGROUND_CHANNEL), const LocalPlatform());

```
note : when I changed it it throw an exception of un handled method or so
2. and the other one is : is there any way that we can send sms even if the app is killed or not running at all (in My case I'm trying to use it with FCM background messages ) ?

**Comment by cescobar2194** [comment]
Hello, did you find a solution to this? I always get an exception
