### ISSUE TITLE
Execution failed for task ':telephony:compileDebugKotlin'

### ISSUE THREAD

**Issue by webdeveloperkanai** [shounakmulay/Telephony#133]
After adding telephony dependency to my project then this error came. Please help me

![image](https://user-images.githubusercontent.com/70555095/160436367-c1c8289b-0e14-478e-a1a5-5317bb5ed27e.png)

![image](https://user-images.githubusercontent.com/70555095/160435986-facddd89-8db7-417a-9c19-4b8940d966de.png)

**Comment by konkomaji** [comment]
I also got this... this need to fix asap... please fix this @shounakmulay

**Comment by Girivaishnav** [comment]
@shounakmulay I also got this.. please fix this error

**Comment by elchomik** [comment]
@shounakmulay and I also got this issue.  Please fix it

**Comment by moraisamilton** [comment]
@shounakmulay   Também estou com mesmo problema, será que pode corrigir?

**Comment by shounakmulay** [comment]
Checkout https://pub.dev/packages/telephony/versions/0.2.0
