### ISSUE TITLE
I can't receive SMS in the background

### ISSUE THREAD

**Issue by JesterVZ** [shounakmulay/Telephony#150]
Hi.
On the emulator and during usb debugging, they are accepted in the background, however, NOTHING happens on the release. The onBackgroundMessage function doesn't even fire.
Thanks in advance for your reply.

**Comment by hamsadev** [comment]
> Hi. On the emulator and during usb debugging, they are accepted in the background, however, NOTHING happens on the release. The onBackgroundMessage function doesn't even fire. Thanks in advance for your reply.

I faced the same problem.
Did you find a solution for it?

**Comment by EngOmarDr** [comment]
> > Hi. On the emulator and during usb debugging, they are accepted in the background, however, NOTHING happens on the release. The onBackgroundMessage function doesn't even fire. Thanks in advance for your reply.
> 
> I faced the same problem. Did you find a solution for it?

I faced the same problem. Did you find a solution for it   ?

**Comment by hamsadev** [comment]
> > > Hi. On the emulator and during usb debugging, they are accepted in the background, however, NOTHING happens on the release. The onBackgroundMessage function doesn't even fire. Thanks in advance for your reply.
> > 
> > 
> > I faced the same problem. Did you find a solution for it?
> 
> I faced the same problem. Did you find a solution for it ?

As I found out, If you exit the app, it will be killed and no longer exist in the background. I created a background service using the flutter_background_service package, and with this, the app was no longer killed and correctly received SMS in the background.

**Comment by msaadev** [comment]
> 

could you share how you did this

**Comment by msaadev** [comment]
@hamsaco how you fix it could you share

**Comment by JesterVZ** [comment]
> > Hi. On the emulator and during usb debugging, they are accepted in the background, however, NOTHING happens on the release. The onBackgroundMessage function doesn't even fire. Thanks in advance for your reply.
> 
> I faced the same problem. Did you find a solution for it?

Yes, I rewrote everything in kotlin, since the task was small))
And so, this is a flutter problem, which cannot normally launch and maintain background processes. Well, either I don't know something :)
