### ISSUE TITLE
Column function is not supporting

### ISSUE THREAD

**Issue by Sreejithtechno** [shounakmulay/Telephony#20]
The name 'Column' is defined in the libraries 'package:flutter/src/widgets/basic.dart' and 'package:telephony/telephony.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.

'Column' isn't a function.
Try correcting the name to match an existing function, or define a method or function named 'Column'.

![image](https://user-images.githubusercontent.com/69035539/89603524-f83a2980-d886-11ea-9b98-40018e16583d.png)

**Comment by Sreejithtechno** [comment]
i found solution try this.
 import 'package:telephony/telephony.dart' hide Column ;

**Comment by shounakmulay** [comment]
The `Column` class is now changed to `TelephonyColumn` in `v0.0.2`.
