### ISSUE TITLE
how to sent more than 160 character 

### ISSUE THREAD

**Issue by Sreejithtechno** [shounakmulay/Telephony#21]
how to sent more than 160 character please show some code

**Comment by shounakmulay** [comment]
Hey @Sreejithtechno,

If your message is longer than 160 characters, you can set the `isMultipart` flag to true.
You can checkout the documentation here: https://shounakmulay.gitbook.io/telephony/sending-an-sms#sendsms

```dart
Telephony telephony = Telephony.instance;

telephony.sendSms(
    to: "1234567890",
    message: "Some very long text...",
    isMultipart: true
    );
```

Hope this solves your query.

**Comment by Sreejithtechno** [comment]
thank you its working
 how to sent multiple number at same time

telephony.sendSms(
    to: "9562144741,9696969696,9898987413",
    message: "Some very long text...",
    isMultipart: true
    );
this code is work nah?

**Comment by shounakmulay** [comment]
So the sendSms function basically passes the string of numbers to send the sms to exactly as you provide it to the sendTextSms function of Android's SmsManager.

As far as I know SmsManager accepts values separated by ';'

Passing numbers like "1234; 658665; 853886" separated by a ; should work.

**Comment by Sreejithtechno** [comment]
i tried not working multiple number. please show some code

**Comment by Sreejithtechno** [comment]
i tried not working multiple number. please show some code
