### ISSUE TITLE
how to sent multiple number at same time

### ISSUE THREAD

**Issue by Sreejithtechno** [shounakmulay/Telephony#25]
how to sent multiple number at same time
show some example code please

**Comment by shounakmulay** [comment]
Hey @Sreejithtechno 

You can pass multiple numbers separated by a `;` 

```dart
await telephony.sendSmsByDefaultApp(
    to: "1234567890;5724352435;24653456345",
    message: "May the force be with you!"
    );
```

It will send the sms to all the numbers. Although keep in mind that this may not work on all devices.


Checkout the [complete documentation here](https://shounakmulay.gitbook.io/telephony/sending-an-sms)

<img src="https://user-images.githubusercontent.com/42094964/92299126-479a7500-ef6d-11ea-93f9-ca9cdc660c55.png" height="800px"/>

<img src="https://user-images.githubusercontent.com/42094964/92299127-48cba200-ef6d-11ea-8491-2e4db9b3f625.png" height="800px"/>

**Comment by samasmith89** [comment]
Attempting to send a message to multiple recipients using the semicolon separated list does not work on my Google Pixel 5.
