### ISSUE TITLE
Listen for events when app is in foreground not work anymore after background isolate is started

### ISSUE THREAD

**Issue by meomap** [shounakmulay/Telephony#30]
Problem reproduction:

- Setup `listenIncomingSms` with both options of `onNewMessage` and `onBackgroundMessage` specified as illustrated at https://github.com/shounakmulay/Telephony/blob/10c53e61c39097c22d7788630ee5133339d1d11a/example/lib/main.dart#L50 

- Open example app, simulate an sms event. `onNewMessage` is triggered as expected.
- Send app to background, resend. `onBackgroundMessage` is triggered and background isolate is started.
- Bring app back to front, resend. `onNewMessage` at dart side shows no sign of receiving event.

It seems that `foregroundSmsChannel?.invokeMethod(ON_MESSAGE, args)` at android side don't work anymore after isolate is executed.

I think the problem is at flutter side that is related to this issue https://github.com/flutter/flutter/issues/23904

**Comment by shounakmulay** [comment]
Thanks @meomap for investigating this.

It looks like there's no one solution agreed upon yet judging by the issue linked above.

**Comment by shounakmulay** [comment]
Hey @meomap,

I have made a fix.

Would be great if you could try out `telephony: 0.0.3` and let me know.

Thanks.

I will close this issue for now.

**Comment by meomap** [comment]
@shounakmulay I upgraded to `0.0.3` and confirmed it works fine. Thanks for the fix!
