### ISSUE TITLE
Multi-sim Sending Support

### ISSUE THREAD

**Issue by litzbalane2017** [shounakmulay/Telephony#34]
Good Day.

I want to thank you for this plugin. I am going over the documentation, but cant seem to find if this plugin currently supports multi sim? Specifically, is there a way to select sim slot 1 or slot 2 in sending SMS? 

Thank you.

**Comment by shounakmulay** [comment]
Hey @litzbalane2017,

Good Day to you too.
Thanks for checking this out.

Currently the plugin uses the default sim for sending a SMS. Although I understand that multi sim support would be an important addition to the plugin.

It would be great if you could share what kind of functionality you have in mind. 
Any suggestions are welcome.

Thanks.

**Comment by litzbalane2017** [comment]
Good Day.

I was thinking of having an option to select which sim slot to use for sending an SMS. I believe no flutter plugin has this feature working yet. 

Thank you for the quick response.

**Comment by ngmatu** [comment]
Telephony marche bien mais pas l'envoie direct sur les versions android inférieure 12

**Comment by wepashka** [comment]
Isn't there any solution with this issue?

**Comment by redanium** [comment]
I'm working on it.

**Comment by seddik** [comment]
> Telephony marche bien mais pas l'envoie direct sur les versions android inférieure 12

@ngmatu 
you can use the source code and add some fix lines like so
tu peux utiliser directement le code source en appliquant ces changements

file : SMSController.kt

after do : flutter clean

source : this amazing guy

[](https://github.com/shounakmulay/Telephony/pull/153)

![image](https://github.com/shounakmulay/Telephony/assets/6674347/a2fa3b7e-f1d6-40ba-a461-6432d2144a13)

![image](https://github.com/shounakmulay/Telephony/assets/6674347/5c4b1907-f528-40da-8a21-e0b329571763)

![image](https://github.com/shounakmulay/Telephony/assets/6674347/9d55fb3f-6983-4499-878f-7b7aedf68ba1)
