### ISSUE TITLE
ensureInitializationComplete must be called after startInitialization

### ISSUE THREAD

**Issue by arashAndroid** [shounakmulay/Telephony#35]
Hi. I am trying to get SMS details when the app is in background or not running. after I receive the SMS, the app crashes in bckground. Please help me fix this.

**STEPS RO REPRODUCE**
1. clone the Telephony Example project
2. run the project in VSCODE without debug mode.
3. Receive SMS while in app or while the app is in background (They give the same error).

I run this on android 8 on LG H990 (LG V20)

Then I get this error:

    E/AndroidRuntime(25457): FATAL EXCEPTION: main
    E/AndroidRuntime(25457): Process: com.example.sms, PID: 25457
    E/AndroidRuntime(25457): java.lang.RuntimeException: Unable to start receiver com.shounakmulay.telephony.sms.IncomingSmsReceiver: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
    E/AndroidRuntime(25457): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3329)
    E/AndroidRuntime(25457): 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
    E/AndroidRuntime(25457): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
    E/AndroidRuntime(25457): 	at android.os.Handler.dispatchMessage(Handler.java:105)
    E/AndroidRuntime(25457): 	at android.os.Looper.loop(Looper.java:164)
    E/AndroidRuntime(25457): 	at android.app.ActivityThread.main(ActivityThread.java:6710)
    E/AndroidRuntime(25457): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime(25457): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    E/AndroidRuntime(25457): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
    E/AndroidRuntime(25457): Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
    E/AndroidRuntime(25457): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:174)
    E/AndroidRuntime(25457): 	at com.shounakmulay.telephony.sms.IncomingSmsReceiver.processInBackground(IncomingSmsHandler.kt:77)
    E/AndroidRuntime(25457): 	at com.shounakmulay.telephony.sms.IncomingSmsReceiver.processIncomingSms(IncomingSmsHandler.kt:69)
    E/AndroidRuntime(25457): 	at com.shounakmulay.telephony.sms.IncomingSmsReceiver.onReceive(IncomingSmsHandler.kt:46)
    E/AndroidRuntime(25457): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3318)
    E/AndroidRuntime(25457): 	... 8 more

Flutter Doctor output:

    Doctor summary (to see all details, run flutter doctor -v):
    [√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
     
    [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [√] Android Studio (version 3.6)
    [√] VS Code (version 1.51.1)
    [√] Connected device (1 available)

    • No issues found!

**Comment by shounakmulay** [comment]
Hey @arashAndroid

Thanks for providing error details. Will look into it.

Would be great if you could let me know what version of the plugin you are using.

**Comment by arashAndroid** [comment]
Hi @shounakmulay 
Thanks for the response.
It's the latest version from develop branch. Because I just cloned and used the example project in it.

**Comment by shounakmulay** [comment]
Hey @arashAndroid,

I have published a new version for the plugin [v0.0.5](https://pub.dev/packages/telephony/versions/0.0.5) with the fix.
Let me know if that works for you.

**Comment by arashAndroid** [comment]
Thanks! @shounakmulay
The problem is now fixed. 
Thanks again for quick response and fix.
