### ISSUE TITLE
Task :telephony:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by jctadios** [shounakmulay/Telephony#38]
e: C:\src\git\flutter\.pub-cache\hosted\pub.dartlang.org\telephony-0.0.5\android\src\main\kotlin\com\shounakmulay\telephony\sms\IncomingSmsHandler.kt: (25, 19):
Unresolved reference: FlutterInjector
e: C:\src\git\flutter\.pub-cache\hosted\pub.dartlang.org\telephony-0.0.5\android\src\main\kotlin\com\shounakmulay\telephony\sms\IncomingSmsHandler.kt: (189, 27):
Unresolved reference: FlutterInjector
...
Task :telephony:compileDebugKotlin FAILED

**Comment by jctadios** [comment]
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.17763.107], locale en-PH)
    • Flutter version 1.17.0 at C:\src\git\flutter
    • Framework revision e6b34c2b5c (7 months ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\xConvic\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\xConvic\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by shounakmulay** [comment]
Hey @jctadios,

`FlutterInjector` is a class introduced in the newer versions of flutter. Your issue should be resolved once you update flutter to the [latest version](https://flutter.dev/docs/development/tools/sdk/releases).

If it is not possible for you to upgrade the flutter sdk, then downgrading the `telephony` plugin to an earlier version should resolve this issue. Try using [`telephony: 0.0.4`](https://pub.dev/packages/telephony/versions/0.0.4)
