### ISSUE TITLE
incoming message divided to two message

### ISSUE THREAD

**Issue by alqadri-prog** [shounakmulay/Telephony#39]
Nice Evening,

I am grateful to you for this plugin, I am facing a problem with listen incoming message, the message body is divided to two message when listen incoming message.
Example :
message : 
-------------------------------------------------------------
شراء عبر نقاط بيع
بطاقة: ******* جيل عمر
من: 2680***
مبلغ: 20.50 rym
لدى: Al qadri co          
في: 2020/10/02 18:07
-----------------------------------------------------
Can you solve it please?

**Comment by shounakmulay** [comment]
Hey @alqadri-prog,

So the telephony plugin does not alter the incoming message that is received by a broadcast receiver on native side in any way.

One thing that could be done to confirm that is actually what is happening is check the message that you receive in the default messaging app.

Would be great if you could check whether the message that you get in the listen method and the one in the default sms app is the same.

**Comment by alqadri-prog** [comment]
Thank you for your reply,

The message is the same,but when I use a telephony plugin the message is
split into two messages.

best regards,

**Comment by shounakmulay** [comment]
Thanks for the clarification @alqadri-prog.

Let me try to replicated the issue with the message you provided.

Will update here about my findings.

**Comment by shounakmulay** [comment]
Hey @alqadri-prog 

Here's what I found.

The message above exceeds the character limits of a standard SMS.

<img width="1440" alt="Screenshot 2020-11-19 at 11 32 07 AM" src="https://user-images.githubusercontent.com/42094964/99628052-659b5000-2a5b-11eb-9d2e-86c10f80119f.png">

So when you send such a sms, it actually generates and sends 2 SMS.

While telephony supports sending such multipart messages, it doesn't yet support receiving multipart messages and combining them as one.

It is a feature that should definitely be added to the plugin.

I will keep this issue open to update when this feature is added to the plugin.

PRs are welcome.

**Comment by alqadri-prog** [comment]
Your cooperation is appreciated.

**Comment by shounakmulay** [comment]
Hey @alqadri-prog,

I have released a new version for the plugin. You should now receive all parts of the sms in one go.

Would be great if you could try [telephony v0.0.6](https://pub.dev/packages/telephony/versions/0.0.6) and confirm that it works for you.

Thanks.

**Comment by alqadri-prog** [comment]
You have my full respect and appreciation dear

It's perfect now.

Thank you.

**Comment by alqadri-prog** [comment]
Hi @Shounak MulaySmall issue when I receive multipart SMS messages white
spaces are added between parts of SMS.Is there a way to receive the message
like the original message..

Example :
شراء عبر نقاط بيع
بطاقة: 6803*** مدى
من: 8829***
مبلغ: 39.00 SAR
لدى: INNOVATION UNION CO
في: 2020/11/10 19:24

  Original Message :
[image: image.png]

Outputting Message :
[image: image.png]
