### ISSUE TITLE
Does it work for reading SMS from my contacts on Android 9?

### ISSUE THREAD

**Issue by cnayan** [shounakmulay/Telephony#42]
I want to monitor incoming messages. Hence listenIncomingSms is important function to me.
I ran your example on my Nokia 8 on Android 9, but it could not read SMS sent from my other phone.

Does this project work?

**Comment by cnayan** [comment]
Strange thing is, the example was able to read promotional SMS from random numbers, but not from my other phone.

**Comment by shounakmulay** [comment]
@cnayan Yes I am able to receive all incoming sms correctly. This behaviour sure is strange.

Have you tried running it on some other devices? Do you face the same problem there?

**Comment by cnayan** [comment]
> Have you tried running it on some other devices? Do you face the same problem there?

I do not have any other device. I'll have to wait to test.

**Comment by shounakmulay** [comment]
Closing this for now.

Feel free to reopen this when you have any updates.
