### ISSUE TITLE
Example code not running

### ISSUE THREAD

**Issue by Oshadha1** [shounakmulay/Telephony#44]
```
Because every version of integration_test from sdk depends on flutter_driver any from sdk which depends on platform 3.0.0-nullsafety.4, every version of integration_test from sdk requires platform 3.0.0-nullsafety.4.
And because every version of telephony depends on platform ^2.0.0, integration_test from sdk is incompatible with telephony.
So, because flutter_app_sms depends on both telephony ^0.0.7 and integration_test any from sdk, version solving failed.
pub get failed (1; So, because flutter_app_sms depends on both telephony ^0.0.7 and integration_test any from sdk, version solving failed.)
```

i get this error when i try to run the example code. could you please help?

**Comment by Oshadha1** [comment]
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.25.0-8.1.pre at C:\src\flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

**Comment by shounakmulay** [comment]
This plugin doesn't yet support dart null safety.
Make sure you are not using the versions of flutter and dart sdk that do not use dart null safety.
