### ISSUE TITLE
how to catch errors and know if message was sent

### ISSUE THREAD

**Issue by mimigithub-prog** [shounakmulay/Telephony#45]
Thanks for this package. Please how do i know if the message was sent or not, i  put a phone number that can never exist , it did't throw an error an error for me, the the message wasn't sent. Please how can I catch this error,I have used try and catch, it didn't work, I used .then, .catchError no error was printed out. Please help, I also used sendStatus, no error was printed out

**Comment by shounakmulay** [comment]
The actual process of sending the sms is delegated to the android system. Hence the only way to know if the sms was sent and delivered is to register intents.
https://github.com/shounakmulay/Telephony/blob/4c25d9c1ce13c671e300c1e9ec0738c2a5802e36/android/src/main/kotlin/com/shounakmulay/telephony/sms/SmsController.kt#L63

To answer your question, in the current state of the plugin, if you do not receive both `SENT` and `DELIVERED` status in the listener, we can conclude that there was an error in sending the sms.

**Comment by shounakmulay** [comment]
Unfortunately this method of detecting an error in the sms sending process in not elegant. Also I won't be able to look more into it in the near future.

I would be happy to accept any PRs to improve this situation.

**Comment by mimigithub-prog** [comment]
Thanks so much,
