### ISSUE TITLE
Is there a way to stop listen incoming sms?

### ISSUE THREAD

**Issue by shinewanna** [shounakmulay/Telephony#47]
`
    _telephony.listenIncomingSms(
      onNewMessage: (SmsMessage message) async {
        List<String> selectedApps = await SharedPref.selectedApps.getList();
        print(selectedApps);
        if (selectedApps.contains('sms')) {
          print("foreground");
          _post({
            'app_name': message.address,
            'msg': message.body,
          });
        }
      },
      listenInBackground: selectedApps.contains('sms'),
      onBackgroundMessage:
          selectedApps.contains('sms') ? backgroundMessageHandler : null,
    );`

i want to trigger listen and unlisten the incoming sms.

**Comment by ali80** [comment]
its seems that setting `onNewMessage` to null does the trick,
`listenIncomingSms` doesn't register a new listener, it just sets the `callback`

**Comment by shounakmulay** [comment]
You can disable the background listening by either setting `onBackgroundMessage` to null or not passing it at all. You can aslo do that by setting `listenInBackground` to false.

As for listening for sms when app is in foreground you cannot turn that off of you have registered a broadcast receiver. As @ali80 said `listenIncomingSms` just sets the callback, the actual broadcast receiver is already present.
Setting it to null is not ideal and could cause issues. 

For the use case you want to support, the proper way would be to actually have a context registered broadcast receiver.
Unfortunately I don't have any plans to do that for now.
I would be happy to accept a PR for it. 

Thanks.
