### ISSUE TITLE
Listening / receiving sms does not work

### ISSUE THREAD

**Issue by ShadeBlack** [shounakmulay/Telephony#55]
Copied the entire example into a new flutter project.
android manifest minsdk 19, 
permissions set, receiver included
connected my phone via usb with android studio.
loaded app and got a friend to send me an sms.
app only ever says 'latest: null'
receiver never seems to fire - adding `print('hi')` doesn't fire in onBackgroundMessage(), or onMessage()
any ideas?

edit: RCS was the issue.

**Comment by Kishan-Somaiya** [comment]
Hello @ShadeBlack Can you tell me what was the issue ? and if possible can you share your code ?

**Comment by ShadeBlack** [comment]
My issue was with [RCS](https://jibe.google.com/). 
If the message was sent by someone with Google RCS enabled, it wouldn't be received as an SMS, but instead an RCS message.
Same problem if the receiving phone has RCS enabled.
I have to have both phones disable RCS completely in order for it to go through correctly.
