### ISSUE TITLE
Fails on latest version of flutter/dart

### ISSUE THREAD

**Issue by syleishere** [shounakmulay/Telephony#56]
Because no versions of path_provider match >2.0.1 <3.0.0 and path_provider 2.0.1 depends on path_provider_platform_interface ^2.0.0, path_provider ^2.0.1 requires path_provider_platform_interface ^2.0.0.
And because path_provider_platform_interface >=2.0.0 depends on platform ^3.0.0 and telephony >=0.0.8 depends on platform ^2.2.1, path_provider ^2.0.1 is incompatible with telephony >=0.0.8.
So, because musicplayer depends on both telephony ^0.0.8 and path_provider ^2.0.1, version solving failed.
pub get failed (1; So, because musicplayer depends on both telephony ^0.0.8 and path_provider ^2.0.1, version solving failed.)

**Comment by shounakmulay** [comment]
This is a dependency conflict.

`path_provider` needs platform `3.0.0` which is a null safe version.
`telephony` needs platform `2.0.1` which is not null safe.

Looks like you migrated some dependencies to null safe version which is causing the conflict. 
Telephony as of now is not null safe.

**Comment by shounakmulay** [comment]
@syleishere I have published a new version of `telephony` that is null safe.
Try using version [0.1.0](https://pub.dev/packages/telephony/versions/0.1.0). You should not have the problem anymore.
