### ISSUE TITLE
Support for MMS - multiple recipients and sending images

### ISSUE THREAD

**Issue by samasmith89** [shounakmulay/Telephony#60]
Really liking the cleanliness and simplicity of this package!  It is missing a few key features however that I'd like to see.  

Sending a message to multiple recipients through MMS would be nice.  I saw that you support this through semicolon separated lists like so:

```dart
await telephony.sendSmsByDefaultApp(
    to: "1234567890;5724352435;24653456345",
    message: "May the force be with you!"
);
```

but this isn't working on my Pixel 5. I'm assuming this is just batch SMS, and not MMS?  Also being able to send images through MMS would be very useful.

**Comment by shounakmulay** [comment]
Thanks for the feature request.

The semicolon separated way of sending sms is solution that is not very consistent. Not many devices support it.
A better option would be to send these sms one by one. 
Maybe the plugin should have something that would do something similar internally.

Unfortunately I do not have any plans in the near future for adding support for this or the MMS and images feature.

Although I would be happy to accept PRs if you or anyone else would like to give it a go.
