### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type 'FutureOr<List<dynamic>>' in type cast

### ISSUE THREAD

**Issue by winnyboy5** [shounakmulay/Telephony#62]
Hi,

Facing the below error when I try to get inbox sms:

`I/flutter (13138): AsyncSnapshot<Object?>(ConnectionState.done, null, type 'Future<dynamic>' is not a subtype of type 'FutureOr<List<dynamic>>' in type cast, #0      Telephony.getInboxSms`

This is my code:

`_onPageLoad() async {
    final Telephony telephony = Telephony.instance;
    bool permissionsGranted = (await telephony.requestSmsPermissions)!;
    if (permissionsGranted) {
      List<SmsMessage> messages = await telephony.getInboxSms();
      print(permissionsGranted);
      print(messages);
      return messages;
    }
    return [];
  }`

Worked only after changing the below line under - telephony.dart:170:

`final List<dynamic> messages = await (_foregroundChannel.invokeMethod(GET_ALL_INBOX_SMS, args) as FutureOr<List<dynamic>>);`

`final List<dynamic> messages = await (_foregroundChannel.invokeMethod(GET_ALL_INBOX_SMS, args) as FutureOr<dynamic>);
`

**Comment by rishisaraf11** [comment]
same here

**Comment by shounakmulay** [comment]
Checkout [v0.1.1](https://pub.dev/packages/telephony/versions/0.1.1). Should be fixed.

**Comment by winnyboy5** [comment]
Thanks for the Update..
