### ISSUE TITLE
Read inbox  throws casting problem

### ISSUE THREAD

**Issue by tomafik** [shounakmulay/Telephony#67]
While trying to read SMS using the following code, I get a casting problem.

 List<SmsMessage> messages = await telephony.getInboxSms()

The error log says, 
Unhandled Exception: type 'List<Object?>' is not a subtype of type 'List<LinkedHashMap<dynamic, dynamic>>?' in type cast

Telephony.getInboxSms (package:telephony/telephony.dart:177:22)

**Comment by shounakmulay** [comment]
Thanks for pointing this out @tomafik 

Will release a fix.

**Comment by shounakmulay** [comment]
Checkout [v0.1.2](https://pub.dev/packages/telephony/versions/0.1.2)
