### ISSUE TITLE
Help needed! I am currently a beginner in flutter ,the example code not working

### ISSUE THREAD

**Issue by skylum1** [shounakmulay/Telephony#70]
Here is the code :
https://pub.dev/packages/telephony/example
The received message  is not displayed (even in foreground) , the openDialer function is working though.

**Comment by skylum1** [comment]
It worked after adding receiver in manifest.  I request you to kindly update the readme such that before query sms we have listen sms so that it is stupid people friendly like me.

**Comment by satyaprakashksingh** [comment]
I was facing the same issue, to fix this You need "RECEIVE_SMS" Permission.  Go to [https://shounakmulay.gitbook.io/telephony/listen-incoming-sms](url)
