### ISSUE TITLE
Question: Can I  use this package to check sms even when app is not open.

### ISSUE THREAD

**Issue by skylum1** [shounakmulay/Telephony#71]
Basically , I want the app to read an sms and check it for a predifened pattern and then ring the phone if the pattern matches.
All this should happen without opening the app. Is it possible ?

**Comment by shounakmulay** [comment]
I don't exactly understand your scenario.
But if you want to listen to incoming sms in the background, you can see the documentation for that.
If you want to just access some sms when app is in background, you can checkout something like work manager and read the sms in background.

**Comment by skylum1** [comment]
I want to read sms when the app is closed (i.e want to run it is as a service )

**Comment by rushib1** [comment]
I had the same issue, Tried the background code. It was not working for me. Then after spending few hours writing plain android code still had the same issue (was working when app is in foreground and background but not when the app was force-closed). Later after trail and error was able to find that my phone's(one plus 8t) battery optimisation was the culprit. So disabling it for the particular app fixed the issue for me. @skylum1

**Comment by skylum1** [comment]
@rushib1 Can you please give more detail on how to detect SMS in background without opening the App ?
The option I believe is running a service

**Comment by rushim1** [comment]
Maybe you have to open it once after installing but later it will work even after the app is killed.

Following this  should be enough to get what you want. https://shounakmulay.gitbook.io/telephony/listen-incoming-sms.
This telephony package will do all the platform specific heavy lifting for you so you that you don't have to worry about it.


Some phone will try to optimise battery usage and not send sms events to non-whitelisted packages. In my case I had to disable battery optimization for the sepcific app(every time you reinstall), this link I found on internet will guide you for multiple brands [disable battery optimisation](https://support.convoy.com/hc/en-us/articles/360053911434-How-to-Disable-Android-Battery-Optimization)
