### ISSUE TITLE
Need context on backgroudHandler

### ISSUE THREAD

**Issue by tluanga** [shounakmulay/Telephony#76]
We need context on the backgroundHandler function, we cant pass any other type other than SmsMessage on the function, so context cannot be pass which we need to have data like SmsAddress

**Comment by shounakmulay** [comment]
Hey @tluanga
I'm not sure I completely understand what you mean by context. 
Could you maybe provide an example of what you would like the api to be like. That would be helpful.

**Comment by shounakmulay** [comment]
Closing this for now.
