### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by torian257x** [shounakmulay/Telephony#79]
your plugin can cause crashes:

solution here:
https://github.com/flutter/flutter/issues/29092#issuecomment-790951623

discussion:
https://github.com/flutter/flutter/issues/81546#issuecomment-831068100

**Comment by shounakmulay** [comment]
Can you please provide more details as to when this happens, and steps to reproduce this?

Thanks.
