### ISSUE TITLE
if I put phone on "hold" and try to send SMS in background and or foreground service, no sms sent

### ISSUE THREAD

**Issue by torian257x** [shounakmulay/Telephony#80]
if I put phone on "hold" and try to send SMS in background and or foreground service, no sms sent

any ideas why that is the case? I have a xiaomi MIUI 9 or so. So they like to suppress stuff, but I turned off battery saver in 2 places.

any ideas?

**Comment by shounakmulay** [comment]
Not exactly sure how android behaves when phone is on hold.

Possibly android restricts background activity while phone is in progress.
