### ISSUE TITLE
Error with Flutter 2.2.0

### ISSUE THREAD

**Issue by mustafa-fahimi** [shounakmulay/Telephony#85]
Hi. Since I updated Flutter to 2.2.0 I get this error and can't use this package.
Error: telephony-0.1.3\android\src\main\kotlin\com\shounakmulay\telephony\sms\SmsMethodCallHandler.kt: (52, 62): Expecting a parameter declaration

**Comment by shounakmulay** [comment]
Duplicate of #84

I will remove the trailing commas in next release.

**Comment by Tokenizer94** [comment]
@shounak-mulay Thanks, man. But when will be the next release? I want to use your package but I can't right now.

**Comment by shounakmulay** [comment]
Fixed in [v0.1.4](https://pub.dev/packages/telephony/versions/0.1.4)
