### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by jasonkaruza** [shounakmulay/Telephony#88]
This works great on Android, so thank you very much for creating it :-) I saw that there is a blocked ticket to add iOS support. Just wondering if there is any timeline on that.

**Comment by shounakmulay** [comment]
Hey @jasonkaruza 
Thank you!

I am not that acquainted with apple devices in general. So at the time of creating the ticket, I was not aware that iOS does not allow access to SMS. 

For sending an SMS, there is already a great package out there that supports both iOS and Android called [flutter_sms](https://pub.dev/packages/flutter_sms).

As for adding iOS support to this package, I don't have any plans for that yet.

**Comment by jasonkaruza** [comment]
Hi @shounakmulay . Thank you for your response. I have an open issue with flutter_sms (https://github.com/fluttercommunity/flutter_sms/issues/45). When running in a headless context, sending SMS doesn't work with their plugin (for me at least) on Android. Whereas yours does :-) That's the reason I was inquiring. 

Either way, great work on this plugin and thank you for creating it.
