### ISSUE TITLE
feature: listen to incoming message when app is not running

### ISSUE THREAD

**Issue by prajwal27** [shounakmulay/Telephony#90]
Hello, I have an application that needs to listen to incoming SMS when the app is not running as well. Is there work being done along that lines? Currently, the package supports listening to incoming SMS when the app is running and also in the background but not when app is closed.

Would like to contribute towards creating this feature :)

**Comment by shounakmulay** [comment]
Hey @prajwal27 

The package does support running when the app is closed. The reason it may not work as expected in most cases is that the device blocks the background execution of the app.

The steps to do this vary on every device but in general disabling battery optimization and on some devices also allowing auto start permission should help.
This website lists ways to do this on various devices: https://dontkillmyapp.com/

**Comment by prajwal27** [comment]
@shounakmulay  
So, is there no additional feature required in the package to support this?

Ex: If I'm using a Samsung device and I enable all the permission which the above link mentions, then r u saying that the package will listen to incoming message when app is closed?

**Comment by shounakmulay** [comment]
Yes technically that should work.

Let me know if you find otherwise.
