### ISSUE TITLE
Some part of data are null

### ISSUE THREAD

**Issue by farokhze** [shounakmulay/Telephony#93]
Hello,
when I call getInboxSms part of the data that I received is null.
![Screenshot (199)](https://user-images.githubusercontent.com/43118428/121130701-0577ca00-c844-11eb-98aa-ca92aa1f3b2b.png)

**Comment by shounakmulay** [comment]
Hey @farokhze 

Telephony only returns those columns that you specify to it. You can have a [look at the default values here](https://shounakmulay.gitbook.io/telephony/query-sms#getinboxsms). 

If even after specifying the columns you get null values then you might need to check what the content resolver on android is actually returning. Telephony just passes on the values from the content resolver to you.
