### ISSUE TITLE
Is an SMS sent when there is no communication network?

### ISSUE THREAD

**Issue by meridorkobi** [shounakmulay/Telephony#94]

**Comment by shounakmulay** [comment]
If the device has no network available then the sms won't get delivered but I think you might be able to see the sms in the default sms app.

**Comment by meridorkobi** [comment]
I closed the WIFI & Mobile Data in my Android Phone.
I sent SMS using Messages app and received in my other Phone.
I sent SMS using Telephony application and the SMS is not in Messages app and was not received in my other Phone

**Comment by shounakmulay** [comment]
I am not sure how the SmsManager on android works in situations like this. I'll have a look.
Would be great if you could also share the code snippet that you are using.

**Comment by meridorkobi** [comment]
Thanks for your cooperation,
I can't share the code but can do a test with code you will share with me
Kobi

**Comment by falahgs** [comment]
hi 
why i get the error 
Restarted application in 3,034ms.
E/flutter ( 6235): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method requestPhoneAndSmsPermissions on channel plugins.shounakmulay.com/foreground_sms_channel)
E/flutter ( 6235): #0      MethodChannel._invokeMethod
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235): #1      _SendSMSstate.initPlatformState
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235):
E/flutter ( 6235): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method openDialer on channel plugins.shounakmulay.com/foreground_sms_channel)
E/flutter ( 6235): #0      MethodChannel._invokeMethod
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235): #1      Telephony.openDialer (package:telephony/telephony.dart:514:5)
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235): #2      _SendSMSstate.build.<anonymous closure>
E/flutter ( 6235): <asynchronous suspension>
E/flutter ( 6235):


i'm using the code 

import 'package:flutter/material.dart';
import 'dart:async';
import 'package:telephony/telephony.dart';

onBackgroundMessage(SmsMessage message) {
  debugPrint("onBackgroundMessage called");
}

//void main() {
// runApp(MyApp());
//}

class SendSMS extends StatefulWidget {
  @override
  _SendSMSstate createState() => _SendSMSstate();
}

class _SendSMSstate extends State<SendSMS> {
  String _message = "";
  final telephony = Telephony.instance;

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  onMessage(SmsMessage message) async {
    setState(() {
      _message = message.body ?? "Error reading message body.";
    });
  }

  onSendStatus(SendStatus status) {
    setState(() {
      _message = status == SendStatus.SENT ? "sent" : "delivered";
    });
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    // Platform messages may fail, so we use a try/catch PlatformException.
    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.

    final bool result = await telephony.requestPhoneAndSmsPermissions;

    if (result != null && result) {
      telephony.listenIncomingSms(
          onNewMessage: onMessage, onBackgroundMessage: onBackgroundMessage);
    }

    if (!mounted) return;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(child: Text("Latest received SMS: $_message")),
          TextButton(
              onPressed: () async {
                await telephony.openDialer("xxxxxxxxxxxx");
              },
              child: Text('Open Dialer'))
        ],
      ),
    ));
  }
}
