### ISSUE TITLE
Block certain incoming messages

### ISSUE THREAD

**Issue by AhsanAmanHunzai** [shounakmulay/Telephony#99]
I wanted to ask if you guys could add this feature. I've also read to block incoming messages in android your app should be a "Default Messaging App" by the user. I wondered if you could implement the system so that when the user makes your app as a default, we will always redirect to the androids SMS app, assuming that we want two different outgoing SMS systems.

**Comment by shounakmulay** [comment]
Yes you are correct. If we want to do anything other than read messages and send messages, the app need to be the default messaging app.

I don't have any plans of implementing the support for this yet. Although I would like to accept PRs if anyone is interested to give it a go.
